//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer3.Contrib.ViewLocalization.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Welcome {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Welcome() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer3.Contrib.ViewLocalization.Resources.Welcome.Welcome", typeof(Welcome).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityServer publishes a &lt;a href=&quot;{{configurationUrlVal}}&quot;&gt;discovery document&lt;/a&gt; where you can find metadata and links to all the endpoints, key material, etc..
        /// </summary>
        internal static string W_ConfigurationMessage {
            get {
                return ResourceManager.GetString("W_ConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to IdentityServer3.
        /// </summary>
        internal static string W_PageHeader {
            get {
                return ResourceManager.GetString("W_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (build {{versionVal}}).
        /// </summary>
        internal static string W_PageSubHeader {
            get {
                return ResourceManager.GetString("W_PageSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdentityServer allows users to view and revoke &lt;a href=&quot;{{permissionsUrlVal}}&quot;&gt;application permissions&lt;/a&gt; previously granted to client applications..
        /// </summary>
        internal static string W_PermissionsMessage {
            get {
                return ResourceManager.GetString("W_PermissionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are links to the &lt;a href=&quot;{{documentationUrlVal}}&quot;&gt;documentation&lt;/a&gt;, and &lt;a href=&quot;{{samplesUrlVal}}&quot;&gt;ready to use samples&lt;/a&gt;..
        /// </summary>
        internal static string W_RefsDocsMessage {
            get {
                return ResourceManager.GetString("W_RefsDocsMessage", resourceCulture);
            }
        }
    }
}
