//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer3.Contrib.ViewLocalization.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Consent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer3.Contrib.ViewLocalization.Resources.Consent.Consent", typeof(Consent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Allow.
        /// </summary>
        internal static string Cons_AllowButton {
            get {
                return ResourceManager.GetString("Cons_AllowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Access.
        /// </summary>
        internal static string Cons_AppAccessPanelHeader {
            get {
                return ResourceManager.GetString("Cons_AppAccessPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, Do Not Allow.
        /// </summary>
        internal static string Cons_DoNotAllowButton {
            get {
                return ResourceManager.GetString("Cons_DoNotAllowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string Cons_ErrorPanelPrefix {
            get {
                return ResourceManager.GetString("Cons_ErrorPanelPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{clientNameVal}} &lt;small&gt;is requesting your permission&lt;/small&gt;.
        /// </summary>
        internal static string Cons_PageHeader {
            get {
                return ResourceManager.GetString("Cons_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string Cons_PersonalInfoPanelHeader {
            get {
                return ResourceManager.GetString("Cons_PersonalInfoPanelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember My Decision.
        /// </summary>
        internal static string Cons_RememberLabel {
            get {
                return ResourceManager.GetString("Cons_RememberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (required).
        /// </summary>
        internal static string Cons_RequiredTip {
            get {
                return ResourceManager.GetString("Cons_RequiredTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck the permissions you do not wish to grant..
        /// </summary>
        internal static string Cons_SubHeaderMessage {
            get {
                return ResourceManager.GetString("Cons_SubHeaderMessage", resourceCulture);
            }
        }
    }
}
